# Change these first
owner: ccris02 # Your GitHub organization or username, where this repository lives
repo: 1KV_API # The name of this repository

# Add your sites here
sites:
#####################
# - Kusama API      #
#####################
  - name: kusama.w3f.community/candidate/address
    url: https://kusama.w3f.community/candidate/Dq97kmsJXGTciU1eMXZMAp4D41Y9e7kQ4hmFBfZW7YD4CCf
    icon: https://raw.githubusercontent.com/ccris02/1KV_API/master/assets/ksm.png
  - name: kusama.w3f.community/erapoints/address
    url: https://kusama.w3f.community/erapoints/Dq97kmsJXGTciU1eMXZMAp4D41Y9e7kQ4hmFBfZW7YD4CCf
    icon: https://raw.githubusercontent.com/ccris02/1KV_API/master/assets/ksm.png
  - name: kusama.w3f.community/score/address
    url: https://kusama.w3f.community/score/Dq97kmsJXGTciU1eMXZMAp4D41Y9e7kQ4hmFBfZW7YD4CCf
    icon: https://raw.githubusercontent.com/ccris02/1KV_API/master/assets/ksm.png
    expectedStatusCodes:
    - 200
    maxResponseTime: 5000
  - name: kusama.w3f.community/candidates
    url: https://kusama.w3f.community/candidates
    icon: https://raw.githubusercontent.com/ccris02/1KV_API/master/assets/ksm.png
    expectedStatusCodes:
    - 200
    maxResponseTime: 5000
  - name: kusama.w3f.community/erastats
    url: https://kusama.w3f.community/erastats
    icon: https://raw.githubusercontent.com/ccris02/1KV_API/master/assets/ksm.png
    expectedStatusCodes:
    - 200
    maxResponseTime: 5000
  - name: kusama.w3f.community/locationstats
    url: https://kusama.w3f.community/locationstats
    icon: https://raw.githubusercontent.com/ccris02/1KV_API/master/assets/ksm.png
    expectedStatusCodes:
    - 200
    maxResponseTime: 5000
#####################
# - Polkadot API    #
#####################
  - name: polkadot.w3f.community/candidate/address
    url: https://polkadot.w3f.community/candidate/149riLdwAVzXg7Cm88RcXhbuFi3zUgwrGsJSSPjC47PRxHQW
    icon: https://raw.githubusercontent.com/ccris02/1KV_API/master/assets/dot.png
    expectedStatusCodes:
    - 200
    maxResponseTime: 5000
  - name: polkadot.w3f.community/erapoints/address
    url: https://polkadot.w3f.community/erapoints/149riLdwAVzXg7Cm88RcXhbuFi3zUgwrGsJSSPjC47PRxHQW
    icon: https://raw.githubusercontent.com/ccris02/1KV_API/master/assets/dot.png
    expectedStatusCodes:
    - 200
    maxResponseTime: 5000
  - name: polkadot.w3f.community/score/address 
    url: https://polkadot.w3f.community/score/149riLdwAVzXg7Cm88RcXhbuFi3zUgwrGsJSSPjC47PRxHQW
    icon: https://raw.githubusercontent.com/ccris02/1KV_API/master/assets/dot.png
    expectedStatusCodes:
    - 200
    maxResponseTime: 5000
  - name: polkadot.w3f.community/candidates
    url: https://polkadot.w3f.community/candidates
    icon: https://raw.githubusercontent.com/ccris02/1KV_API/master/assets/dot.png
    expectedStatusCodes:
    - 200
    maxResponseTime: 5000
  - name: polkadot.w3f.community/erastats 
    url: https://polkadot.w3f.community/erastats
    icon: https://raw.githubusercontent.com/ccris02/1KV_API/master/assets/dot.png
    expectedStatusCodes:
    - 200
    maxResponseTime: 5000
  - name: polkadot.w3f.community/locationstats
    url:  https://polkadot.w3f.community/locationstats
    icon: https://raw.githubusercontent.com/ccris02/1KV_API/master/assets/dot.png
    expectedStatusCodes:
    - 200
    maxResponseTime: 5000
  - name: Test site
    url: https://google.com
    icon: https://raw.githubusercontent.com/ccris02/1KV_API/master/assets/google.png

commitMessages:
  commitAuthorName: "1kv Bot"

status-website:
  theme: dark
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /1KV_API
  #themeUrl: https://raw.githubusercontent.com/ccris02/1KV_API/master/assets/custom-theme.css
  logoUrl: https://raw.githubusercontent.com/ccris02/1KV_API/master/assets/VegasLifeLight.jpg
  name: 1KV API Uptime
  introTitle: "**1KV API Upptime** is monitor current status of W3F API."
  navbar:
    - title: Status
      href: /1KV_API
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
